Set runtime to "python3.9" since python 3.7 is deprecated and cannot be handled by google cloud app engine
fixing => "ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Error(s) encountered validating runtime. Runtime python37 is end of support and no longer allowed. Please use the latest Python runtime for App Engine Standard..
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/gcloud" failed: step exited with non-zero status: 1"